### ISSUE TITLE
Some problems about list

### ISSUE THREAD

**Issue by alim0x** [nana-4/Flat-Plat#1]
![screenshot from 2015-10-27 19-42-42](https://cloud.githubusercontent.com/assets/4954007/10757056/261047c2-7ce3-11e5-857f-660b648a9c19.png)

When it's in the middle of scrollable content,  there will be dashed line in the top or bottom, seems to be a bug.

By the way, I think the top-bar's height, 32px, is a little thick, I think around 26px will be better, to screen usage and to be pleasing to eyes.

Gnome 3.16

**Comment by MichaelTiebesl** [comment]
I have installed Arch with Gnome 3.18. For me it looks very nice the dashed line. I like the details. Also the top-bar height looks good to me. 

![schermafdruk van 2015-10-28 09-20-39](https://cloud.githubusercontent.com/assets/10792019/10777337/6c54d226-7d55-11e5-968c-283d6c08a58b.png)

**Comment by alim0x** [comment]
top-bar height absolutely have no problem, I just think if it can be more slim, maybe will be more friendly to laptop user, because the laptop's screen size is not big enough, slim top-bar looks good when you maximize window

**Comment by nana-4** [comment]
I admit that 2px width dash sometimes looks noisy. However, 1px is a bit hard to find at a glance.

I think around 26px is a bit too slim on desktop. (I was tested on 28px.) This theme widgets are designed slightly bigger to be good for high-resolution.

So, unfortunately I do not change them at the moment.

**Comment by sevachka** [comment]
hey,
I also thought this is a bug. Is there an easy way to remover these "stiches" (dash)? Does look like a bug on both of my screens (14" FHD and 25" QHD).

**Comment by nana-4** [comment]
@sevachka 
> Is there an easy way to remover these "stiches" (dash)?

Yes. 

1. Open `gtk-3.0/gtk.css` and `gtk-3.0/gtk-dark.css` with text editor.
2. Find `.undershoot.*` around 2338 lines.
3. Edit code like this:

> 
.undershoot.top {
  background-color: transparent;
  background-image: linear-gradient(to left, rgba(255, 255, 255, 0.2) 50%, rgba(0, 0, 0, 0.2) 50%);
  padding-top: **1px**;
  background-size:  **10px 1px**;
  background-repeat: repeat-x;
  background-origin: content-box;
  background-position: center top; }
> 

* Bold = changes
