### ISSUE TITLE
App menu for files too compact when set inside window

### ISSUE THREAD

**Issue by Teslator** [nana-4/Flat-Plat#100]
The file's app menu have paddings problems when not set on the top bar :

![capture d ecran de 2017-01-17 15-33-36](https://cloud.githubusercontent.com/assets/9469099/22024758/5796d33a-dccb-11e6-9e5f-8445d802845b.png)

Setup :
- Flat-plat latest version on 17th january 2017
- GTK+ 3.22.6
- Fedora 25
- Gnome 3.22
- File application 3.22.2

**Comment by knight-corvi** [comment]
@Teslator Sorry to ask here, but what extensions are you using to merge the Top-Bar with the Application-bar?
Thank you

**Comment by Teslator** [comment]
It's a fork from the Zorin Taskbar called Dash to Panel. It's available on github at this address :
https://github.com/jderose9/dash-to-panel

More on WOGUE's Google plus page : https://plus.google.com/+WorldofGnomeOrg

You just have to clone the branch and compile it.

**Comment by knight-corvi** [comment]
@Teslator Alright, thank you. I will look into it.

**Comment by cthbleachbit** [comment]
Seems only the case with nautilus. Other programs using this feature still draw normal menu.

**Comment by nana-4** [comment]
Sorry for the delay in my response. Thanks for your report!
