### ISSUE TITLE
Window preview functionality of dash-to-panel extension is broken with flatplat

### ISSUE THREAD

**Issue by libcg** [nana-4/Flat-Plat#101]
* flatplat 20161227
* gnome-shell 3.22.2
* arch linux

This theme creates a gap between the window preview popup and the panel. As a result, the popup will often disappear when moving the mouse to select a window. This doesn't happen with the default shell theme.

https://github.com/jderose9/dash-to-panel/issues/42
https://github.com/jderose9/dash-to-panel/issues/19

**Comment by nana-4** [comment]
My apologies for the late reply...

Previously I confirmed this issue, but now it seems to be almost solved in the upstream current version.
I think that it would be better to visually have a gap between the panel and the popup, so I won't make changes this time. Sorry.

Anyway, thanks for the report!
