### ISSUE TITLE
Not an issue. How to install the latest version of this theme?

### ISSUE THREAD

**Issue by USBA** [nana-4/Flat-Plat#104]
This is not an issue.
How to install latest version (not the latest release) using terminal commands ?

I'm sorry @nana-4 for opening an issue for this stupid question. Please help me.
Thanks.

**Comment by nana-4** [comment]
It's OK. ;)

It just change `v20161227` to `master` as with [this page](https://github.com/nana-4/Flat-Plat#manual-installation).

```sh
cd /tmp
curl -sL https://github.com/nana-4/Flat-Plat/archive/master.tar.gz | tar xz
cd Flat-Plat-master && sudo ./install.sh
```

**Comment by nana-4** [comment]
It is also OK to download and unzip the archive then run `sudo ./install.sh`.

**Comment by USBA** [comment]
Thank you so much
