### ISSUE TITLE
Flat-Plat-dark and Flat-Plat-dark-compact gnome-shell theme missing VPNs toggle switch.

### ISSUE THREAD

**Issue by xpduyson** [nana-4/Flat-Plat#108]
- Flat-Plat version: Flat-Plat-20170323
- GTK+ 3 version: 3.22.2
- Distribution: Debian Sid
- Desktop environment: Gnome 3.22.2

**Flat-Plat-dark-compact**
![screenshot from 2017-03-24 21-22-02](https://cloud.githubusercontent.com/assets/6981890/24298237/f522247a-10d7-11e7-9454-30398cc6cd13.png)

**Flat-Plat-light-compact**
![screenshot from 2017-03-24 21-21-39](https://cloud.githubusercontent.com/assets/6981890/24298236/f52042ea-10d7-11e7-8e11-7852f002e810.png)

**Comment by nana-4** [comment]
I could not reproduce it. Please try to uninstall the theme then install it again.

**Comment by xpduyson** [comment]
Reinstall and the issue is gone. Thank you.
