### ISSUE TITLE
GDM Login Theme, missing gresource

### ISSUE THREAD

**Issue by ianhattendorf** [nana-4/Flat-Plat#109]
Fedora 25
Flat-Plat 20170323-1.fc25
GTK+ 3.22.10-1.fc25
Gnome 3.22.3-1.fc25
GTK+ and shell-theme are set to Flat-Plat

I'm following the instructions for `GDM (Lock/Login Screen)`, however there's no `gnome-shell-theme.gresource` file in `/usr/share/themes/Flat-Plat/gnome-shell`. Am I missing something?

**Comment by nana-4** [comment]
Thanks for your report.

I confirmed this issue by installing from the [Copr repository](https://copr.fedorainfracloud.org/coprs/tcg/themes/).
 But I'm not its maintainer. So @LaurentTreguier, could you fix this bug?

**Comment by LaurentTreguier** [comment]
I'll look into it

**Comment by LaurentTreguier** [comment]
I see where the prbblem comes from. I missed the `glib-compile-resources` usage in the `install.sh` file, thus the `.gresource` files cannot be compiled on Copr. I'll correct the specfile and post a new build shortly.

**Comment by LaurentTreguier** [comment]
The new package seems to be fine on my end. Can you confirm on yours ?

**Comment by ianhattendorf** [comment]
Great, thanks for the fast response. It's there and working now.

One thing I noticed while upgrading (`dnf upgrade --refresh`) was that it said it was skipping the `src` package since it had broken dependencies. Does this need to be installed? I thought when I installed it (`dnf install Flat-Plate-theme`) it just installed the `noarch` package?
```
Upgrading:
 Flat-Plat-theme      noarch      20170323-2.fc25         tcg-themes      772 k
Skipping packages with broken dependencies:
 Flat-Plat-theme      src         20170323-2.fc25         tcg-themes      650 k
```

**Comment by ianhattendorf** [comment]
Oh, and I also noticed that while the login screen wallpaper changed, the lock screen wallpaper (the one that shows the time, before pressing space to get to the password prompt) is still the default from fedora. Is this expected?

**Comment by LaurentTreguier** [comment]
I tried to build the package twice, and canceled the first build. I've had weird things like this when doing it and I'll try to fix this, but you shouldn't have to worry about it.

However regarding the lockscreen wallpaper I have no idea...

**Comment by LaurentTreguier** [comment]
Shouldn't the lockscreen wallpaper be user-decided in the system settings ?

**Comment by ianhattendorf** [comment]
Ah you're right, I keep forgetting the lock screen background is user selectable while login isn't. Looks like everything's working now then, thanks for the help!

**Comment by nana-4** [comment]
@LaurentTreguier Thanks for your support!
