### ISSUE TITLE
Show if a windows has focus

### ISSUE THREAD

**Issue by Diego-BF** [nana-4/Flat-Plat#11]
When using your theme, I cannot see if a window has focus or not. In the first screenshot here in the Flat-Plat git you can see this issue. Maybe you can change the fonts or window color for something slightly different when the window does not have the focus.

P.S. Thank you for this beautiful theme and sorry for my english :-)

**Comment by robotmaxtron** [comment]
:+1:

**Comment by Salamandar** [comment]
+1 !
