### ISSUE TITLE
Can the GDM theming be used with LightDM?

### ISSUE THREAD

**Issue by andrew820** [nana-4/Flat-Plat#110]
No bug, one question.

First things first, I love the theme, really great work :)

Now, the question:
Can this beautiful theme, specifically the login shell, be used with LightDM?

I tried applying the theme to the lightdm-gtk-greeter, but it only colored the login box.

**Comment by nana-4** [comment]
Hi,

Unfortunately, we cannot apply GDM theme to LightDM. It's technically impossible.

But if you are using GTK+ 3.20 or higher, LightDM should look like the screenshot below.
![image](https://cloud.githubusercontent.com/assets/9556384/24834276/21645b62-1d1b-11e7-8f95-784c7d5fe90c.png)

> I tried applying the theme to the lightdm-gtk-greeter, but it only colored the login box.

I suppose you're using GTK+ 3.18.x. But for now, Flat-Plat for GTK+ 3.18 does not properly support LightDM theme. If you have a request, I would like to support it for GTK+ 3.18. :)

**Comment by nana-4** [comment]
Since there's no response, I'd like to close this.
