### ISSUE TITLE
Notification area weird colors

### ISSUE THREAD

**Issue by flipflop97** [nana-4/Flat-Plat#115]
![screenshot from 2017-05-14 19-05-20](https://cloud.githubusercontent.com/assets/13943260/26036174/3565f790-38d9-11e7-9266-1eddfc137ac4.png)

The Notification area seems off since I updated Gnome to 3.24. The above screenshot shows how it looks when hovering over the weather area. Both the colors from this highlighted weather area and the vertical seperation line seem too dark.

Flat-Plat Light 1:3.22.20170323-1 (from AUR)
GTK+ 3.22.15
Arch Linux
Gnome 3.24.2

**Comment by nana-4** [comment]
Thank you for the report.

Perhaps you updated or installed the theme before updating gnome to 3.24, so your `gnome-shell` theme of Flat-Plat is still for `3.22`. So please try to re-install the theme. 😃

**Comment by flipflop97** [comment]
Thanks! Reinstalling completely fixed it.
