### ISSUE TITLE
Highlight focused item in Budgie Menu

### ISSUE THREAD

**Issue by swarnendubiswas** [nana-4/Flat-Plat#117]
If you report a bug or ask a question, please include the following information as required:
- Flat-Plat version 20170515
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`) 3.22.11
- Distribution (and version) Ubuntu Gnome 17.04
- Desktop environment (and version) Budgie 10.3.1
- Related application (and version)
- Steps to reproduce
Open the Menu and try to focus on one item with keyboard. The applications/entries should be highlighted to allow distinguishing (as in say Arc).
- Screenshot(s)
Print Screen shortcut isn't working for some reason currently, I will try to post a picture later.

**Comment by nana-4** [comment]
Thank you for your report.
I confirmed this issue. :)
