### ISSUE TITLE
Geary application

### ISSUE THREAD

**Issue by sharifzadesina** [nana-4/Flat-Plat#118]
- Flat-Plat version: Arch AUR
- GTK+ 3 version: 3.22.15
- Distribution: ArchLinux
- Desktop environment and version:  GNOME  3.24.2
- Related application and version: Geary makepkg~g00718198 (I think latest version)
- Steps to reproduce: Open the Geary application you will see the below screenshot :D
- Screenshot(s):
![screenshot from 2017-05-28 16-59-11](https://cloud.githubusercontent.com/assets/15300551/26528744/e560a35a-43c6-11e7-8907-4a501b746f3f.png)

As you can see in the screenshot (zoom in the red square) there is an extra shadow before menu.

P.S. I am really glad to see your theme is now more standard and has really clean code, keep good work up ;)

**Comment by nana-4** [comment]
Thank you for your report. 😄 
I confirmed this issue.

I will fix it when my current work finishes. 😃
