### ISSUE TITLE
master branch doesnt support gnome 3.14 (metacity)

### ISSUE THREAD

**Issue by whdgmawkd** [nana-4/Flat-Plat#12]
gnome-tweak-tool on Gnome 3.14
Windows theme never shows Flat-Plat.
GTK theme shows Flat-Plat.
your 3.14 branch is many different compared to master
If you have time, can you add legacy metacity support on master branch?

**Comment by nana-4** [comment]
My apologies for the late reply...

Honestly, I don't want to support so old versions because I don't have much time for development.
However, I would like to re-support the Metacity for compatibility. ;)

**Comment by nana-4** [comment]
It was supported with 1b44bf7a575a735b61820ee6774ec6f05ef8f09a.
