### ISSUE TITLE
[Install] Cannot Stat Files

### ISSUE THREAD

**Issue by alex285** [nana-4/Flat-Plat#120]
on `install.sh` script, `L8`
https://github.com/nana-4/Flat-Plat/blob/master/install.sh#L8

you have
```
gnomever=$(gnome-shell --version | cut -d ' ' -f 3 | cut -d . -f -2)
```

since i use GNOME 3.26 (3.25 devel) that returns
```
3.25
```
therefore the `gnomever` is set to `3.25` and the script cant copy the assets. i know you dont support 3.26 yet, but for the people that do use a development version of GNOME, can you please take into account the `3.25`? 

which btw it works fine, apart that commit that breaks opacity a bit

On Shell
https://git.gnome.org/browse/gnome-shell/commit/?id=447bf55e45b00426ed908b1b1035f472c2466956

On Shell CSS
https://git.gnome.org/browse/gnome-shell-sass/commit/?id=4c361179a1d45544dcbfbac209c1842aae171a01

**Comment by nana-4** [comment]
Thank you for your report. Certainly we should consider the development versions of GNOME. :)

> which btw it works fine, apart that commit that breaks opacity a bit

Exactly. I'm also going to work on that someday, as I mentioned in #114. :D

**Comment by Skehmatics** [comment]
Couldn't this be fixed by PR #119?

**Comment by nana-4** [comment]
@Skehmatics Frankly speaking, I'm not sure, but it's probably not enough... (Sorry but I'm very amateur about shell script. :P)

**Comment by nana-4** [comment]
Fixed.
Please let me know if any problems remain. I'd reopen this.

**Comment by alex285** [comment]
yes it is fixed, thanks!
