### ISSUE TITLE
Menu bar is not following the title bar colour on some applications

### ISSUE THREAD

**Issue by TechnoSparks** [nana-4/Flat-Plat#121]
*Disclaimer: Not sure if non-existent feature (the colour of the title bar is not meant to be changed) or a bug*

**Flat-Plat Version:** v20170605
**GTK+ 3 version:** 3.22.15
**Distribution:** Manjaro (rolling release)
**Desktop environment**: Gnome 3.24.2
**Related application:** So far Pinta and Atom editor

## Steps to reproduce
1. Change theme's default colour for title bar from `blue_grey` to `green`
2. Parse SCSS
3. Install the theme
4. Restart shell
5. Open affected applications

## Additional notes
I am not so sure what is going on here. At first I thought that you might somewhere hard coded the `blue_grey` somewhere, but I have no idea on how to create/assess a theme, hence making troubleshooting relating scss files difficult.

Confusion also hardens when some applications abide with the colour change without any issues (refer Terminal screenshot below. Transmission bittorrent client is also not affected)

I am also suspecting that there would be also other applications with this issue, since this is a general flaw.

## Screenshot(s)
*Nautilus with correctly applied title bar colour*
![screenshot from 2017-06-06 10-44-56](https://cloud.githubusercontent.com/assets/6072210/26812086/453e1694-4aa8-11e7-86e0-c4d5ea285ca7.png)

*Terminal with menu bar follows the title bar colour*
![screenshot from 2017-06-06 10-44-58](https://cloud.githubusercontent.com/assets/6072210/26812089/48e09a92-4aa8-11e7-9b67-4b7ba7809246.png)

*Pinta with menu bar not following the title bar colour*
![screenshot from 2017-06-06 10-45-00](https://cloud.githubusercontent.com/assets/6072210/26812130/7ab21456-4aa8-11e7-9157-865f20765dea.png)

*Atom with menu bar the same like Pinta*
![screenshot from 2017-06-06 11-09-02](https://cloud.githubusercontent.com/assets/6072210/26812162/9f0c24ea-4aa8-11e7-8849-50c546902c46.png)

**Comment by nana-4** [comment]
Thank you for the clear report.

This problem is because Pinta and Atom are GTK2 based apps.

Terminal is a GTK3 app, so it can be changed the colors via SCSS/CSS. However, in order to change the colors of the GTK2 apps, you need to edit inside `src/gtk-2.0/` directory.

For example, to change the GTK2 menu bar color, simply open `src/gtk-2.0/gtkrc` and change the `#455A64` string. 😃

**Comment by TechnoSparks** [comment]
Thank you! Fixed this on the spot, and learnt something new 😇 Sorry for the report - I thought it was a bug

**Comment by nana-4** [comment]
@TechnoSparks It’s all right :)
