### ISSUE TITLE
Not an issue: Question how to change everything that is pink to something else, like blue.

### ISSUE THREAD

**Issue by alothings** [nana-4/Flat-Plat#124]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

If you report a bug or ask a question, please include the following information as required:
- Flat-Plat version
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Distribution (and version)
- Desktop environment (and version)
- Related application (and version)
- Steps to reproduce
- Screenshot(s)

**Comment by nana-4** [comment]
You can change the _accent color_ by the following procedure. Also please refer to [`HACKING.md`](https://github.com/nana-4/Flat-Plat/blob/master/HACKING.md) for details.

1. Clone or download source files.

1. Open `src/gtk-3.0/3.22/sass/_colors.scss` and `src/gnome-shell/3.18/sass/_colors.scss` then change the `$pink_A200` string to your favorite color.

2. Run `./parse-sass.sh` on the repo directory.

3. Change the assets color with reference to [`HACKING.md#how-to-change-the-assets-color`](https://github.com/nana-4/Flat-Plat/blob/master/HACKING.md#how-to-change-the-assets-color).

4. Finally, run `sudo ./install.sh`.

**Comment by nana-4** [comment]
You can also use [Flat-Plat-Blue](https://github.com/peterychuang/Flat-Plat-Blue) which is the forked theme, btw. :)

**Comment by nana-4** [comment]
No response, so I'd like to close this.
