### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by ddnexus** [nana-4/Flat-Plat#127]
The log reports quite a lot "Did not find color property '-gradient-start'" and "Did not find color property '-gradient-end'".

There is an interesting discussion about the cause and the solution to the problem here:

https://github.com/linuxmint/Cinnamon/issues/6034

The issue appear also with Ubuntu GNOME.
-----
- Flat-Plat version LATEST master
- GTK+ 3 version LATEST
- Ubuntu GNOME latest

**Comment by cthbleachbit** [comment]
Cannot reproduce on Archlinux with Master branch and gtk3+ 3.22 and gnome 3.24. Please specify what the "latest" version is because different distributions can have very different versions of the same software.

**Comment by nana-4** [comment]
I'm sorry for the late reply.

Unfortunately, I also couldn't reproduce this on Fedora 26 with GNOME Shell 3.24.3. :-(

Until `gnome-shell 3.24`, the upstream theme also included `-gradient-start` and` -gradient-end` properties, so the warning message sounds odd...

See: https://github.com/GNOME/gnome-shell/blob/gnome-3-24/data/theme/gnome-shell.css#L1134

**Comment by nana-4** [comment]
In any case, third-party `gnome-shell` themes **must** always overwrite the upstream Adwaita theme. This means, even if we remove the properties in Flat-Plat, it is meaningless because the upstream includes them.

This issue might be better to report to the upstream `gnome-shell`.
