### ISSUE TITLE
Steps for setting up Dash to Dock theming

### ISSUE THREAD

**Issue by jacobcantele** [nana-4/Flat-Plat#129]
Flat Plat is currently advertising that it supports the customization of Dash to Dock, but it isn't clear what that consists of (no screenshots, etc.) and it is not clear how to enable it. Would it be possible to get more info, and get clarification added to the Flat Plat page?

**Comment by nana-4** [comment]
No need any special settings for Dash to Dock. Just install the theme is okay.
We just added specific _styling_ for Dash to Dock to suit this theme. That includes:
- Space adjustments
- Indicators for fitting this theme
- Recolorable background color between desktop and overview
- Other minor styling for Dash to Dock's abilities

And [this screenshot](https://github.com/nana-4/Flat-Plat#gnome-shell) shows how Dash to Dock appears in Flat-Plat. Do you think this is still not enough?

**Comment by jacobcantele** [comment]
Got it, that makes sense, Nana. Thank you very much.
