### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by rahilwazir** [nana-4/Flat-Plat#14]
Any future plan to fully support Unity?

**Comment by nana-4** [comment]
I'd like to support Unity.
However, I have many other stuffs to do before that.
Therefore, please do not expect it immediately. ;)

**Comment by nana-4** [comment]
Added Unity support for now :)

**Comment by rahilwazir** [comment]
@nana-4 How it suppose to look in Ubuntu? It looks terrible though 😄 

Screenshot:
![flat-plat-unity](https://cloud.githubusercontent.com/assets/1818941/17462528/c92ebd3c-5cc9-11e6-9129-bc0e427597f0.png)

**Comment by nana-4** [comment]
Hmm, maybe you're using the wrong version of the theme. Flat-Plat currently supports only Ubuntu 16.04 and it uses GTK+ 3.18.x. So you should get this theme from `3.18` branch or [here](https://github.com/nana-4/Flat-Plat/archive/3.18.zip).

**Comment by rahilwazir** [comment]
@nana-4 Yes, you are right, was using `3.20`. Now installed `3.18` which looks quite better.

One problem is that the titles on menu and top bar suppose to be white? It's unreadable.

![white_titles](https://cloud.githubusercontent.com/assets/1818941/17506931/269b07d4-5e26-11e6-9025-212fa7703dba.png)

**Comment by nana-4** [comment]
@rahilwazir That's weird. Will it be white even if you reboot your system?

**Comment by rahilwazir** [comment]
@nana-4 Yes, even restarted :disappointed:

**Comment by nana-4** [comment]
@rahilwazir I'm sorry for the late reply. I was changed color scheme of the theme 2cd76e49eb9c4719d76143bd78fc8a572333b43f, so I believe that it was fixed...

**Comment by rahilwazir** [comment]
@nana-4 You mean it's fixed now on branch [3.18](https://github.com/nana-4/Flat-Plat/tree/3.18)?

**Comment by rahilwazir** [comment]
@nana-4 Nevermind, just clone the branch [3.18](https://github.com/nana-4/Flat-Plat/tree/3.18). Now it looks great. Thanks!
