### ISSUE TITLE
 [Suggestion] GNOME-Shell dropdown arrows

### ISSUE THREAD

**Issue by archqob** [nana-4/Flat-Plat#145]
Personally i use [Remove Dropdown Arrows](https://extensions.gnome.org/extension/800/remove-dropdown-arrows/) to remove dropdown arrows from top bar. I think it would be great if you implemented this tweak to the theme, It looks better without these arrows.
**What do you think ?**

**Comment by nana-4** [comment]
Thanks for the suggestion. but I personally like the dropdown arrows. Also, as far as I know, we cannot remove the arrows by the themes.

**Comment by archqob** [comment]
> as far as I know, we cannot remove the arrows by the themes.

Actually, we can do that.
i think this is the part of code from [United-GNOME](https://github.com/godlyranchdressing/United-GNOME) theme is responsible for dropdown arrows.
```
#panel .popup-menu-arrow {
  min-width: 0px !important;
  width: 0px !important;
  padding: 0px !important;
  -natural-hpadding: 0px !important;
  height: 0px;
```

**Comment by nana-4** [comment]
Aha, you are right.

But even if we can do that by the themes, honesty I do not like to delete it. I think it would be better for users to freely add or delete it with the extention. So I won't delete it. Sorry.
