### ISSUE TITLE
Help in creating a Flat-Plat base16 theme for Tilix

### ISSUE THREAD

**Issue by OriginalFannibal** [nana-4/Flat-Plat#146]
I would like to create a base16 theme based on Flat-Plat. It would work as a color palette for not only  Tilix but even a lot of other projects that accept base16 templates (including Gnome Terminal) so it could be ported to them.

The following constitute the base16 color palette:

    base00 - Default Background
    base01 - Lighter Background (Used for status bars)
    base02 - Selection Background
    base03 - Comments, Invisibles, Line Highlighting
    base04 - Dark Foreground (Used for status bars)
    base05 - Default Foreground, Caret, Delimiters, Operators
    base06 - Light Foreground (Not often used)
    base07 - Light Background (Not often used)
    base08 - Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
    base09 - Integers, Boolean, Constants, XML Attributes, Markup Link Url
    base0A - Classes, Markup Bold, Search Text Background
    base0B - Strings, Inherited Class, Markup Code, Diff Inserted
    base0C - Support, Regular Expressions, Escape Characters, Markup Quotes
    base0D - Functions, Methods, Attribute IDs, Headings
    base0E - Keywords, Storage, Selector, Markup Italic, Diff Changed
    base0F - Deprecated, Opening/Closing Embedded Language Tags e.g. <?php ?>

There's a lot of information here: http://chriskempson.com/projects/base16/

Could you kindly share the corresponding Flat-Plat colors so that I could try making the theme? Ideally, the background color would integrate seamlessly with the GTK header bar color but if you don't think that's a good fit for a terminal background then please provide whatever color you think would be suitable.

**Comment by nana-4** [comment]
Have you seen the [`HACKING.md`](https://github.com/nana-4/Flat-Plat/blob/master/HACKING.md)?

For Sass, used in gtk3 and gnome-shell, just edit the `_colors.scss` files.

For example, in order to apply base16 to the gtk3 theme, try replacing the code in `src/gtk-3.0/3.22/sass/_colors.scss` as follows (then run `./parse-sass.sh` and `sudo ./install.sh`. Note that this is a quick hack and _this_ color scheme is not tested very much):

```scss// When color definition differs for dark and light variant,
// it gets @if ed depending on $variant

@import 'color-palette';

$base00: #181818;
$base01: #282828;
$base02: #383838;
$base03: #585858;
$base04: #b8b8b8;
$base05: #d8d8d8;
$base06: #e8e8e8;
$base07: #f8f8f8;
$base08: #ab4642;
$base09: #dc9656;
$base0A: #f7ca88;
$base0B: #a1b56c;
$base0C: #86c1b9;
$base0D: #7cafc2;
$base0E: #ba8baf;
$base0F: #a16946;

@function gtkalpha($c, $a) {
  @return unquote("alpha(#{$c}, #{$a})");
}

// Foreground colors
$dark_fg_color:   $base02;
$light_fg_color:  $base05;
$button_fg_color: if($variant == 'light', $base02, $base05); // extra fg color for raised buttons

$fg_color:                    if($variant == 'light', $base02, $base05);
$secondary_fg_color:          rgba($fg_color, 0.7);
$hint_fg_color:               rgba($fg_color, 0.5);
$disabled_fg_color:           rgba($fg_color, 0.5);
$disabled_secondary_fg_color: rgba($fg_color, 0.3);
$track_color:                 rgba($fg_color, 0.3);
$divider_color:               rgba($fg_color, 0.12);

$titlebar_fg_color:                    if($titlebar == 'light', $base02, $base05);
$titlebar_secondary_fg_color:          rgba($titlebar_fg_color, 0.7);
$titlebar_hint_fg_color:               rgba($titlebar_fg_color, 0.5);
$titlebar_disabled_fg_color:           rgba($titlebar_fg_color, 0.5);
$titlebar_disabled_secondary_fg_color: rgba($titlebar_fg_color, 0.3);
$titlebar_track_color:                 rgba($titlebar_fg_color, 0.3);
$titlebar_divider_color:               rgba($titlebar_fg_color, 0.12);

$inverse_fg_color:                    $base05;
$inverse_secondary_fg_color:          rgba($inverse_fg_color, 0.7);
$inverse_hint_fg_color:               rgba($inverse_fg_color, 0.5);
$inverse_disabled_fg_color:           rgba($inverse_fg_color, 0.5);
$inverse_disabled_secondary_fg_color: rgba($inverse_fg_color, 0.3);
$inverse_track_color:                 rgba($inverse_fg_color, 0.3);
$inverse_divider_color:               rgba($inverse_fg_color, 0.12);

// Background colors
$bg_color:         if($variant == 'light', $base06, $base00);
$base_color:       if($variant == 'light', $base07, $base01);
$alt_base_color:   mix($base_color, $bg_color, 50%);
$lighter_bg_color: $base_color;
$darker_bg_color:  $bg_color;

$titlebar_bg_color:     if($titlebar == 'dark', $base01, $base05);
$alt_titlebar_bg_color: if($titlebar == 'dark', $base01, $base05);
$panel_bg_color:        if($titlebar == 'dark', $base00, rgba($black, $middle_opacity));
$unity_panel_bg_color:  if($titlebar == 'dark', $base00, $base04); // translucent colors cannot be used for Unity and MATE panels
$alt_panel_bg_color:    rgba($black, $lower_opacity);

$fill_color:      gtkalpha(currentColor, $lower_opacity);
$semi_fill_color: gtkalpha(currentColor, $lower_opacity / 2);
$row_fill_color:  gtkalpha(currentColor, 0.05);

// Misc colors
$primary_color:         $base02;
$alt_primary_color:     $base03;
$accent_color:          $base08;
$disabled_accent_color: rgba($accent_color, 0.5);

$link_color:         $base0D;
$visited_link_color: $base0E;

$warning_color: $base09;
$error_color:   $base08;
$success_color: $base0B;

$suggested_color:   $accent_color;
$destructive_color: $base08;

$info_bg_color:     $base0E;
$question_bg_color: $base0D;
$warning_bg_color:  $base09;
$error_bg_color:    $base08;

$border_color:             if($variant == 'light', rgba($black, 0.12), rgba($black, 0.3));
$highlight_color:          if($variant == 'light', rgba($white, 0.4),  rgba($white, 0.1));
$titlebar_highlight_color: if($titlebar == 'dark', rgba($white, 0.1),  rgba($white, 0.4));
$unity_highlight_color:    if($titlebar == 'dark', rgba($white, 0.1),  rgba($white, 0.2));
$alt_highlight_color:      rgba($white, 0.2); // for selection-mode headerbar which colored with primary color
$titlebar_indicator_color: if($titlebar == 'dark', currentColor, $primary_color);

// FIXME: gtk's @placeholder_text_color API really should use $secondary_fg_color,
// but it doesn't work with translucent colors. So we use opaque colors instead.
$placeholder_text_color: mix($fg_color, $base_color, percentage(0.7));
```

**Comment by nana-4** [comment]
JFYI, there's already a fork of Flat-Plat based on base16:
https://github.com/asmolero/Flat-Plat-base16

**Comment by nana-4** [comment]
You can also refer to this comment to change the color scheme:
https://github.com/nana-4/Flat-Plat/issues/128#issuecomment-325116620

**Comment by OriginalFannibal** [comment]
Thanks for replying. The documentation you've provided in `HACKING.md` is amazing!

I think you misunderstood my request though. I didn't want to make a base16 version of Flat-Plat but to make a base16 terminal theme using Flat-Plat's colors, so that my terminal integrated better with the rest of the theme.

I found [Materia](https://github.com/Defman21/base16-materia-scheme) and it looks great with Flat-Plat so that's what I am using.

Once again, thank you so much for all your amazing work on the theme :)

**Comment by nana-4** [comment]
Oh, I completely misunderstood... Sorry. 😅
