### ISSUE TITLE
Window close icons in gnome shell have a weird animation

### ISSUE THREAD

**Issue by tttom64** [nana-4/Flat-Plat#147]
Currently, hovering over window close icons in the GNOME shell overview behaves weirdly. A few of the top pixels move up and then come back down.

Actual behavior should resemble [Adapta](https://github.com/adapta-project/adapta-gtk-theme), where window buttons have a separate .svg for mouseover and pressed.

**Comment by nana-4** [comment]
Thank you for the report. But,

> Actual behavior should resemble Adapta, where window buttons have a separate .svg for mouseover and pressed.

Adapta is a fork of Flat-Plat, so that's obvious why it _resemble_...

**Comment by tttom64** [comment]
Hopefully you can see the problem from this gif. I tried adding a new window-close-hover.svg, which worked in changing the color, but the strange animation persisted.

![output](https://user-images.githubusercontent.com/13117753/30689408-5f087c0c-9eb0-11e7-8869-7c24b7dc384d.gif)

**Comment by tttom64** [comment]
also, this problem doesn't happen when moving from active to hover (which animates the shadows).

**Comment by nana-4** [comment]
Thanks for the additional info. Fixed.

**Comment by tttom64** [comment]
So if I'm correct, you made the transition instant? Or is it disabled altogether?

**Comment by nana-4** [comment]
Yeah, I disabled the transition because when `-st-background-image-shadow` property is animated, the button seems to distort. (I believe this is a bug of the upstream `gnome-shell`, rather than a bug of this theme.)

**Comment by tttom64** [comment]
What I meant to ask was, does the shadow still change despite the animation being disabled?

**Comment by nana-4** [comment]
Yes. The shadow still change without animation. See:
https://github.com/nana-4/Flat-Plat/blob/master/src/gnome-shell/3.26/gnome-shell.css#L1593-L1604
