### ISSUE TITLE
Wrong font color in Synaptic

### ISSUE THREAD

**Issue by swarnendubiswas** [nana-4/Flat-Plat#152]
If you report a bug or ask a question, please include the following information as required:
- Flat-Plat version 
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`) 3.22.21
- Distribution (and version) Ubuntu Gnome 17.10
- Desktop environment (and version) Budgie desktop 10.4.0
- Related application (and version) Synaptic
- Steps to reproduce
* Open Synaptic, and press Reload.
- Screenshot(s)
![screenshot from 2017-09-28 22 36 44](https://user-images.githubusercontent.com/7343807/31000213-985717c6-a49f-11e7-8158-011dee211c24.png)

**Comment by nana-4** [comment]
Thank you for the report. It's now fixed.
