### ISSUE TITLE
GTK 3.20 support

### ISSUE THREAD

**Issue by Salamandar** [nana-4/Flat-Plat#16]
Well, I just installed Gtk3.19 and almost all Gtk3 themes are broken, due to lots of CSS selectors changes.
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update
Themes now need a separated file for Gtk3.19+.
Are you already working on this ?

**Comment by nana-4** [comment]
I'm not working yet, but I'm going to support GNOME/GTK 3.20 in the near future.

**Comment by chmuibk** [comment]
This would be wonderful, as gnome320 is around the cornber (beta is out).

**Comment by bugaevc** [comment]
+1

**Comment by nana-4** [comment]
It supported (some time ago :smiley:).
