### ISSUE TITLE
[Request] Dark Flat-Plat Gnome-shell Theme.

### ISSUE THREAD

**Issue by 0x221E** [nana-4/Flat-Plat#2]
I love the Flat-plat theme and it looks awesome when "Global Dark Theme" enabled. 
However, the gnome-shell theme is light and it doesn't look fine to my eyes.

![screenshot from 2015-10-28 07-22-34](https://cloud.githubusercontent.com/assets/10757422/10777785/17fdee16-7d45-11e5-8f91-01fe9c7a2f81.png)

Is it possible to have dark-variant of Gnome-shell theme ? Which would look awesome with my dark-variant of Flat-plat gtk theme.
Thanks for such an awesome theme.

**Comment by nana-4** [comment]
Thanks :)

Yeah, I have a plan to make complete dark theme. But to complete this work, we need some important tasks. Therefore, it becomes a little later to be released.(a few weeks after, maybe?)

**Comment by 0x221E** [comment]
@nana-4 Thanks for informing! :+1:

**Comment by pincopallino93** [comment]
The dark theme is fantastic, i am waiting for dark shell theme too.
Thank you so much!

**Comment by cthbleachbit** [comment]
Dark themes are cool!

**Comment by AtomskJD** [comment]
:+1:

**Comment by nahtnam** [comment]
:+1:

**Comment by nobol** [comment]
:+1:

**Comment by nana-4** [comment]
I apologize that it didn't go as planned.
Because it doesn't go very well to make the images for dark theme, I was frustrated it. 
However, I'll get down to this work again. So please wait a little while.

**Comment by cthbleachbit** [comment]
So, turning on the global dark theme would apply to both gnome shell theme and gtk theme?

**Comment by nahtnam** [comment]
:+1:

**Comment by Adrian-Benavente** [comment]
I loved this theme, when a dark version is out, I'll be the first in line to try it.

**Comment by mpkh** [comment]
:+1:

**Comment by marcelopm** [comment]
:+1:

**Comment by pms1969** [comment]
:+1: 

Great theme, easily the best I've seen, and I use it daily.

FYI, on high DPI monitors, `Roboto Light` looks a lot better than `Roboto` as a backup font.  I don't have the M+ fonts, so I've changed it around.  Might be worth a HiDPI version :-)

**Comment by mbacou** [comment]
I second everyone here. Best dark theme on gnome 3.20 (compact version). Kudos! Awaiting a complete dark gnome-shell with transparency as well.
I also wonder if there's a way for the gnome-shell CSS to simply use a **user's default system font** (on HiDPI displays font sizes need to be adjusted manually otherwise).

**Comment by nana-4** [comment]
@pms1969 Thank you for your information. However, this [material design guideline](https://material.io/guidelines/style/typography.html#typography-styles) does not suggest using `light` weight fonts for normal _body_ (`Body 1`), so I hesitate to change `Roboto` to `Roboto Light` with this repo. In addition, there is no way to change fonts only for HiDPI version. Therefore, I think it is better for each user to change the fonts by oneself. :)

**Comment by nana-4** [comment]
@mbacou Thank you, but aren't you enabling "**Large Text**"?

![image](https://cloud.githubusercontent.com/assets/9556384/23688982/118d1c44-03fb-11e7-906a-ca910e4a352c.png)

I don't have a HiDPI display, so I don't know if it is correct, but at least from your screenshot it doesn't look like HiDPI. In any case, as far as I know, there is no way to use the **user's system font size** for gnome-shell. I also hope so the upstream devs support it.

**Comment by mbacou** [comment]
OK thanks, guess I'll have to adjust font sizes manually then. FYI my current display is 125 dpi -- so not HiDPI strictly speaking, but high enough that I need to apply a text scaling factor, so that a 9pt font on my screen actually looks like a 9pt font. At the moment that scaling doesn't play nicely with `gnome-shell.css`.

**Comment by nana-4** [comment]
@mbacou I see... Your information was helpful. Thanks.

**Comment by nana-4** [comment]
I'm so sorry that the correspondence was very delayed.
Finally, global dark theme was supported!

For transparency top bar, which had some requests, I'd like to implement it if [this](https://bugzilla.gnome.org/show_bug.cgi?id=747163) is supported by upstream.
Alternatively, using [Dynamic Panel Transparency](https://extensions.gnome.org/extension/1011/dynamic-panel-transparency/) is also good solution for now.
