### ISSUE TITLE
Packaging for ArchLinux

### ISSUE THREAD

**Issue by cthbleachbit** [nana-4/Flat-Plat#20]
I've set up AUR repositories [flatplat-theme](https://aur4.archlinux.org/packages/flatplat-theme/) (Github Releases) and [flatplat-theme-git](https://aur4.archlinux.org/packages/flatplat-theme-git/) (Cutting-edge git version).

Just to inform about that.

I should send an e-mail to the owner but the e-mail address is not public.

**Comment by nana-4** [comment]
I grasped it. Thanks!
