### ISSUE TITLE
Bug in Nautilus

### ISSUE THREAD

**Issue by sevachka** [nana-4/Flat-Plat#21]
There is a bug in nautilus. By selecting a tab, there is a frame around the content. When I click inside the nautilus window, it will disappear.
![nautilus_bug](https://cloud.githubusercontent.com/assets/11356897/13574930/a1e0ef86-e486-11e5-8b32-bc0b2241bae2.png)

**Comment by nana-4** [comment]
It is by design. It shows the focus state.

**Comment by sevachka** [comment]
okay, strange thing. It is already focused by the white colour. Sorry for this "bug" report. :)
