### ISSUE TITLE
always autoplay

### ISSUE THREAD

**Issue by sevachka** [nana-4/Flat-Plat#23]
hey,
with the newest release, I cannot turn off autoplay. So it always starts playing the latest playback after opening Lollypop. No matter which option I am turning on/off.
Another bug I saw: the playback button (left upper corner) is always showing "play". Never "stop" or "pause".

Edit: I am using Arch-Linux with newest updates (gnome 3.18.x).

**Comment by cthbleachbit** [comment]
Autoplay? Rhythmbox music player?

**Comment by sevachka** [comment]
![lollypop](https://cloud.githubusercontent.com/assets/11356897/14047127/e4faa94a-f2b6-11e5-8b02-ed4eaaf429ab.png)
no, I am talking about Lollypop, like I wrote. There is an option which allows to continue playing where you have stopped before closing. So I open Lollypop, and without pressing a button it is starting from wehre I left... 
I hope now it is clearer what I am talking about.

**Comment by cthbleachbit** [comment]
Anyway, uncheck that underlined restore state option and it'll be back to normal again

![screenshot from 2016-03-25 23-26-53](https://cloud.githubusercontent.com/assets/3353318/14047280/eb6baa88-f2e1-11e5-998d-79dec79545a1.png)

**Comment by sevachka** [comment]
Thank you, that helped. Strangely. I was sure I tried it already. Which theme are you using, by the way?

**Comment by cthbleachbit** [comment]
That's flatplat dark theme variant, Play/pause button works perfectly on my desktop.

![screen1 ogv](https://cloud.githubusercontent.com/assets/3353318/14047596/c8dedb96-f2e3-11e5-8cdd-360591151afb.gif)
