### ISSUE TITLE
Hover on "Home" tab in Files(nautilus)

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#25]
Hey man! First of all, the best flat theme for Gnome 3 Ive ever seen, really great job.

I have one issue, "Home" tab acts weird on hover event - size of "Home" tab is changing.

![screenshot from 2016-04-01 16-31-57](https://cloud.githubusercontent.com/assets/11137173/14210085/bfb3bf70-f827-11e5-8b10-017ea1257314.png)
![screenshot from 2016-04-01 16-32-01](https://cloud.githubusercontent.com/assets/11137173/14210099/c723c6c4-f827-11e5-9ed5-cf5afdd82898.png)

**Comment by Salamandar** [comment]
I don't have this weird problem. Maybe a Nautilus update fixed it ?

**Comment by cthbleachbit** [comment]
Neither on mine. ( on Apr 10 2016 nautilus got upgraded from 3.18.5 to 3.20.0 to use gtk 3.20 )
