### ISSUE TITLE
Popup application window position

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#26]
Is this a normal position for popup application window?
![screenshot from 2016-04-01 17-03-24](https://cloud.githubusercontent.com/assets/11137173/14211009/009f2a5c-f82c-11e5-9421-87347dfa7fe7.png)

**Comment by nana-4** [comment]
It looks wrong position. However, all of the themes that disable popup's arrow seems to become like this.

I think this is the gnome-shell's issue.
