### ISSUE TITLE
Gnome Builder built-in terminal has white text on white background

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#27]
I think that background of built-in terminal should has the same color as rest of the window.

![screenshot from 2016-04-01 17-39-11](https://cloud.githubusercontent.com/assets/11137173/14212128/a99cc77c-f831-11e5-90e8-7403b563fa17.png)

**Comment by Salamandar** [comment]
It's a bug related to Gnome-Builder, I talked to cherger about that some months ago and *it seems* to be solved.

**Comment by nana-4** [comment]
It has become late, but I just fixed it to make sure.
