### ISSUE TITLE
Gnome Software progressbar doesnt have borders

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#28]
I think that progress bar should have some borders or at least shadows:
![screenshot from 2016-04-01 17-49-25](https://cloud.githubusercontent.com/assets/11137173/14212533/ab0d1e20-f833-11e5-8456-8d5fb76ee16e.png)

**Comment by nana-4** [comment]
???
I think that its behavior does not differ with adwaita.
![screenshot from 2016-04-09 07-17-04](https://cloud.githubusercontent.com/assets/9556384/14399085/793cefdc-fe24-11e5-9b14-2045d632fe20.png)

**Comment by Salamandar** [comment]
Yes it does differ : In Adwaita there are borders for us to see where is the "end" of the progressbar. Here, we don't know.
