### ISSUE TITLE
Not full circle in Lollypop app

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#29]
Circle which is placed around some headbar icons is not full:
1. This is ok:
![screenshot from 2016-04-01 19-38-47](https://cloud.githubusercontent.com/assets/11137173/14215206/d47f0454-f841-11e5-96a5-547ab840cf60.png)
2. This is not:
![screenshot from 2016-04-01 19-38-42](https://cloud.githubusercontent.com/assets/11137173/14215213/de6cca6e-f841-11e5-8af9-f38e6276cc0b.png)
3. And this is not ok too:
![screenshot from 2016-04-01 19-38-50](https://cloud.githubusercontent.com/assets/11137173/14215224/eaf01dae-f841-11e5-812f-8e359c2522f8.png)

**Comment by Corsseir** [comment]
```/***************
 * Header bars *
 ***************/

.titlebar,
.header-bar {
  padding: 0.5em; //was $container_padding;```

This seems to solve my issue. It works for 5px too.

**Comment by nana-4** [comment]
Hmm, it seems to set the sizes in the app side.
If we adopt this method, it will be affected to the size of the other apps.
I think this is Lollypop's issue, not mine. :(

**Comment by Salamandar** [comment]
Yeah, I saw this bug in other themes too, for Lollypop. :/

**Comment by nana-4** [comment]
It seems to be fixed by upstream changes. So I close this issue.
