### ISSUE TITLE
(Request) Another wallpaper GDM

### ISSUE THREAD

**Issue by sevachka** [nana-4/Flat-Plat#3]
Hey,

I love your theme.. as you might already know. :)
Politely I wanted to ask you to switch to another wallpaper for the GDM-login screen. 
This one looks just too much iOS like... for my taste. :)

You should consider to accept paypal donations. :)

**Comment by nana-4** [comment]
**Please suggest me what kind of wallpaper is better, everyone** :+1: 

You can also change background image by yourself:

1. Download and extract source code archive from [here](https://github.com/nana-4/Flat-Plat/releases).
2. Replace `noise-texture.png` in extracted `gnome-shell` directory with **same name**.
3. In terminal, move to `gnome-shell` directory.

  ```
  $ cd ~/Downloads/Flat-Plat/gnome-shell
  ```
4. Make new binary file.

  ```
  $ ./gnome-shell-theme.gresource.sh
  ```
5. Replace an existing file with a generated file.

  ```
  $ cp gnome-shell-theme.gresource /usr/share/gnome-shell
  ```
6. Restart GNOME Shell. (press `Alt`+`F2`, then type `r`)

> The referring page:
>  https://wiki.archlinux.org/index.php/GDM

PS: I'll consider about donations, thanks. :smiley:

**Comment by cthbleachbit** [comment]
Any material-ish is fine.

**Comment by sevachka** [comment]
good comment! :D It really took me long to look for a simple but yet not boring wallpaper. I do not want a very dark wallpaper since notebook screens are usually not high-quality ones and I absolutely dislike "glowing" corners etc.... 
I took a look at deviant-art (for inspiration or maybe the creater offers nicely to use his wallpaper).
This are the ones I did like with my GDM-login screen:

1. http://www.deviantart.com/art/Xeon-SLiM-Theme-327079468
2. http://www.deviantart.com/art/Caledonia-KDM-215292557

I could imagine these two wallpapers for your GDM-login.

Thank you again for your work!

**Comment by cthbleachbit** [comment]
but these wallpapers don't comply with GPLv3.

**Comment by sevachka** [comment]
Simple as they are, I do not see any reason not to "re-draw" them.

**Comment by sevachka** [comment]
is there an easy to keep the original gdm-wallpaper and use your login-design? :)

**Comment by sevachka** [comment]
By the way: meanwhile I use a solid color background. I like it because it doesn´t show backlight bleed on LCD-Screens and yet it is still nice to the eye. Probably I´d prefer an ever darker color. But just a tad. 

![noise-texture](https://cloud.githubusercontent.com/assets/11356897/12138640/635b2da8-b46b-11e5-9210-f50702818f98.png)
![noise-texture 2](https://cloud.githubusercontent.com/assets/11356897/12138641/635b7aa6-b46b-11e5-92e8-505177e7e13d.png)

**Comment by nana-4** [comment]
I am terribly sorry about responding so late...
Now, I changed GDM wallpaper based on Material Design color pallet with slight radial gradient.
![image](https://cloud.githubusercontent.com/assets/9556384/13436734/fc7d7af2-e023-11e5-9e1b-f14219d613f1.png)
What do you think? Is it OK? You guys comments became very helpful resource. :smile:

**Comment by robotmaxtron** [comment]
:+1: I like it a lot.

**Comment by sevachka** [comment]
I really do like it! Thanks!
