### ISSUE TITLE
Awful toolbar/osd in Gnome Boxes

### ISSUE THREAD

**Issue by Corsseir** [nana-4/Flat-Plat#30]
The toolbar/osd in Gnome Boxes is just awful :)
![screenshot from 2016-04-08 16-28-33](https://cloud.githubusercontent.com/assets/11137173/14387122/1642e99e-fda8-11e5-8e9e-01a8aff2a09c.png)

**Comment by nana-4** [comment]
I'm sorry for the delayed response, but I can't reproduce it.
What version of Gnome Boxes are you using?

**Comment by nana-4** [comment]
There is no response so I'll close the issue.
But if you have any questions, please feel free to ask again.
