### ISSUE TITLE
Gtk3.20 : very big margins ?

### ISSUE THREAD

**Issue by Salamandar** [nana-4/Flat-Plat#31]
Okay, i don't know how much time you spent on the 3.20 version of the theme, but I LOVE IT ! It's simply sublime !

BUT :
* You should have a folder `gtk-3.20` AND `gtk-3.0` to keep supporting the pre-gtk3.18 versions of GTK.
* The margins seem really bigger than with gtk3.18. Gtk3-widget-factory doesn't even fit my screen !
![capture du 2016-04-11 10-57-08](https://cloud.githubusercontent.com/assets/6552989/14421870/2642c926-ffd4-11e5-81ca-7c192fa2c4ea.png)

**Comment by nana-4** [comment]
I'm sorry for late reply.
I was added a smaller size version for a small-resolution screen. So please try `gtk_laptop.css` and `gtk-dark_laptop.css` after rename them.
