### ISSUE TITLE
Fading for the menus

### ISSUE THREAD

**Issue by Salamandar** [nana-4/Flat-Plat#32]
The drop-down menus (File, Edition,…) apparition is not animated.
It's not a bug, it would just be great to have a fading/"moving" animation. Like for the popovers.
https://www.youtube.com/watch?v=vBM2Ys62Klc
I know it's possible, I've already seen in a theme.

**Comment by nana-4** [comment]
I daringly turned off the fading because it is annoyed for me. :/
