### ISSUE TITLE
Weird radiobuttons on Firefox / Libreoffice

### ISSUE THREAD

**Issue by ed-torvalds** [nana-4/Flat-Plat#34]
I am on Arch Linux using GNOME 3.20 and using Flat Plat 3.20 20160404. checkboxes in Firefox are not visible when they are not checked (although they are visible when they are checked).
Thanks

**Comment by cthbleachbit** [comment]
Yes and radio buttons are not supposed to be like this
![screenshot from 2016-04-18 15-59-02](https://cloud.githubusercontent.com/assets/3353318/14597368/d520ca2e-057e-11e6-8383-77a5af3390af.png)

**Comment by Salamandar** [comment]
…And the scrollbar seems to have disappeared as well.
Maybe it's a Firefox bug due to the whole gtk3.20 changes ?

**Comment by cthbleachbit** [comment]
Libreoffice also experienced inconsistency with gtk3.20 .
![screenshot from 2016-03-25 23-26-53](https://cloud.githubusercontent.com/assets/3353318/14805075/5e593674-0b9b-11e6-99f0-c1b76f434d34.png)

**Comment by cthbleachbit** [comment]
Clear now. Libreoffice and Firefox are still using gtk2 (somehow managed to take on gtk3 themes). However gtk3.20 upgrade broke the consistency. Forcing the gtk3.20 theme on those apps won't make the elements show correctly.

**Comment by cthbleachbit** [comment]
the checkboxes are actually white squares. However the white background makes them invisible
![screenshot from 2016-05-07 11-00-39](https://cloud.githubusercontent.com/assets/3353318/15089934/5e04b0e4-1443-11e6-9dce-8896f0d7d4fe.png)

**Comment by vitriol** [comment]
bummer, no fix?

**Comment by stlaz** [comment]
bump, any signs of proper fix?

**Comment by nana-4** [comment]
I am so sorry for the late response.

I was fixed the phenomenon in which buttons turns white.
But it is hard to resolve the status of the radiobuttons at the moment. (unless it sacrifice animations...)

**Comment by sharifzadesina** [comment]
Gnome 3.18

Radio buttons:
LibreOffice:
![2016-08-27_14-45-03](https://cloud.githubusercontent.com/assets/15300551/18030379/08ab192e-6cc9-11e6-967a-ee3e0ecd34ed.png)

Check boxes:
LibreOffice:
![2016-08-27_14-58-07](https://cloud.githubusercontent.com/assets/15300551/18030380/26fbc9f0-6cc9-11e6-825d-45b9b4895efc.png)
Terminal:
![2016-08-27_14-59-03](https://cloud.githubusercontent.com/assets/15300551/18030387/5d72a882-6cc9-11e6-902d-008db2ed8549.png)

Should be same with Terminal's.

**Comment by nana-4** [comment]
@sharifzadesina It seems that the size of checkboxes is fixed to 15px on LibreOffice of the GTK2 version.
On LibreOffice of the GTK3 version (5.2 or higher), it was solved, so I would like you to wait it.

**Comment by Salamandar** [comment]
Great ! :)

**Comment by nathaneltitane** [comment]
experiencing same issue under certain qt4/qt5 dependant apps.

See attached screen cap.

![screenshot from 2016-09-10 20-05-29](https://cloud.githubusercontent.com/assets/5674757/18414344/4baf299e-7792-11e6-908d-e09f27497b87.png)

**Comment by nana-4** [comment]
@nathaneltitane Hmm, okay, I'll reconsider about check/radiobuttons sizing. Thanks. 👍

**Comment by nana-4** [comment]
Now radiobuttons issues on Firefox is almost gone.

This problem still remains in LibreOffice, but I'd like to clarify the (duplicate) issues, so I opened a new issue as #122 and #123.

So I'd like to close this now, but thank you for your report. :)
