### ISSUE TITLE
Applying the shell theme crashes the GNOME Shell

### ISSUE THREAD

**Issue by yejingchen** [nana-4/Flat-Plat#4]
I got this archive by using the command `git clone https://github.com/nana-4/Flat-Plat.git`

When I use `gnome-tweak-tool` to change the gnome shell theme, all the windows freeze, and the 'Something has gone wrong' screen shows up. I had no choice but to log out.

After logging back in, the User Themes extension was disabled, or I would not have chance to use my laptop again.

I grabbed a log file using `gnome-tweak-tool |& tee gnome-tweak-tool.log.txt`, but I have no idea how to send to you (GitHub says I heed write permission to upload a file in this editing area).

Please let me know how I can provide more detailed information, because I am longing for this theme :)

**Comment by yejingchen** [comment]
My laptop is Lenovo Y460, Intel i3 M380, my OS is Fedora 22 Workstation with GNOME 3.16.2

And I have no idea where this is a bug in this theme or in user-themes.

**Comment by nana-4** [comment]
Oh, sorry for your crashes, but this git `master` branch is made for GNOME 3.18.
Please try the following command to choose `3.16` branch, and check whether it work.

    git checkout 3.16

By the way, it is usually safer to get the archives from here:
https://github.com/nana-4/Flat-Plat/releases

**Comment by yejingchen** [comment]
That works! Now they look perfectly fine, and some other minor problems are gone :)

BTW, I think cloning a git repo is convenient because I want to get updates without frequently checking the webpage...
