### ISSUE TITLE
Invisible radiobuttons and checkboxes in epiphany

### ISSUE THREAD

**Issue by asclepius** [nana-4/Flat-Plat#40]
Using commit bf0583e6767989af59d7dc231b41739c1051e24c

Arch linux 

gnome 3.20

Epiphany does not show check boxes until they are ticked.

![screenshot from 2016-05-06 10-48-20](https://cloud.githubusercontent.com/assets/1190743/15079957/d009f404-1378-11e6-8703-73de9aaf444f.png)

![screenshot from 2016-05-06 10-53-47](https://cloud.githubusercontent.com/assets/1190743/15079972/e9c3906c-1378-11e6-99c9-ebb8cf3f1916.png)

**Comment by cthbleachbit** [comment]
please check how radio boxes look like, it might be a duplicate of issue #34

**Comment by asclepius** [comment]
This is a duplicate of #34
