### ISSUE TITLE
Checkbox not visible when checked in Nautilus

### ISSUE THREAD

**Issue by ed-torvalds** [nana-4/Flat-Plat#41]
I am on Arch Linux running GNOME 3.20.1. I am using this theme (of course).

checkboxes are not visible in Tags tab of Properties window of Nautilus when checked. (see image https://transfer.sh/McnZQ/6096 )

Thanks for your theme, cheers!

**Comment by cthbleachbit** [comment]
It works perfect on my Arch with gtk3.20 . Why not do a `sudo pacman -Syu` to check if everything is updated.
![screenshot from 2016-05-07 20-04-51](https://cloud.githubusercontent.com/assets/3353318/15092006/3727cb90-148f-11e6-8b24-5d72414977ed.png)

**Comment by ed-torvalds** [comment]
Ok, the problem is only with me, thanks for reply.
