### ISSUE TITLE
Opaque version?

### ISSUE THREAD

**Issue by user501254** [nana-4/Flat-Plat#42]
Hi,
Excellent theme. I have been using it for a while now.
Is there a possibility that you could add a non transparent version of the  shell theme into the repo?

**Comment by nana-4** [comment]
I'm so sorry for my late reply.
Unfortunately, there is no plan to add a non transparent version, but some widgets in newer master repo has become opaque.

**Comment by user501254** [comment]
No problem. Thanks for the great theme. :+1:
