### ISSUE TITLE
Question : notebook bottom border

### ISSUE THREAD

**Issue by Arsakes** [nana-4/Flat-Plat#46]
Derar @nana-4  How can I achieve this [effect](http://i63.tinypic.com/200ehw5.png)? In my custom gtk theme? I mean the page button has no border  and doesn't differ from background except for the bottom blue bar.
(Im using murraine engine)

**Comment by nana-4** [comment]
I'm sorry for the late reply.
Are you talking about GTK2 theming? If you so, unfortunately, there is no way to achieve it, AFAIK.

**Comment by nana-4** [comment]
There is no response so I'll close the issue.
But if you have any questions, please feel free to ask again.

**Comment by Arsakes** [comment]
You can close, yes it was about GTK2 theming.
Thanks.
