### ISSUE TITLE
Progress bar 

### ISSUE THREAD

**Issue by MichaelTiebesl** [nana-4/Flat-Plat#5]
The progress bar where i can see how long the process will take is not correctly i think. 
In Adwaita for example, i can see how that the progress bar is slowly getting blue from the left side to the right, until the process is finished. In Flat Plat the process bar is directly full with blue color from the beginning until the end of process. 

![adwaita](https://cloud.githubusercontent.com/assets/10792019/10861042/a92c4192-7fae-11e5-8c87-744056b077ad.png)

![flatplat](https://cloud.githubusercontent.com/assets/10792019/10861043/ae7a83ac-7fae-11e5-83d6-49ac42193fcb.png)

**Comment by Salamandar** [comment]
Yes, I got the same problem sometimes : It's more and more opaque with progress.

**Comment by nana-4** [comment]
Thank you for bug report.
I'm going to fix it.

**Comment by MichaelTiebesl** [comment]
I saw that [https://github.com/tista500/Adapta](url) has forked from Flat-Plat.
I already tested it. I can see the progress bar is with Adapta working how it should be. Maybe you can take a look at that to fix it with your theme?

**Comment by nana-4** [comment]
@MichaelTiebesl I just changed a image(`ProgressBar/trough.png`) from semi-transparent to opaque to fix it.

**Comment by MichaelTiebesl** [comment]
@nana-4 Thanks for the update.

**Comment by nana-4** [comment]
@MichaelTiebesl No problem!
