### ISSUE TITLE
Rebuilding GTK2 assets shows missing elements in assets.svg.

### ISSUE THREAD

**Issue by jayarc** [nana-4/Flat-Plat#50]
If I clone the repo and leave the static assets how they are initially, things look ok. When I go and make a change and run ./render-bits to update the assets from assets.svg I get the following errors because the assets.txt is looking for some IDs in the assets.svg that you don't have in there (any longer?). Here's the missing files for me:

** (inkscape:20571): WARNING **: Object with id="Buttons_flat-button" was not found in the document. Nothing exported.

** (inkscape:20598): WARNING **: Object with id="Buttons_flat-button-insensitive" was not found in the document. Nothing exported.

** (inkscape:20606): WARNING **: Object with id="Buttons_checked-flat-button" was not found in the document. Nothing exported.

** (inkscape:20614): WARNING **: Object with id="Buttons_checked-flat-button-hover" was not found in the document. Nothing exported.

** (inkscape:20622): WARNING **: Object with id="Buttons_checked-flat-button-active" was not found in the document. Nothing exported.

** (inkscape:20632): WARNING **: Object with id="Buttons_checked-flat-button-insensitive" was not found in the document. Nothing exported.

I have looked in the assets.svg for gtk 2 and verified that I don't see those ids. Any ideas? This causes checkboxes in nautilus and other locations to appear as a magenta square.

**Comment by nana-4** [comment]
Exactly, the current GTK2 theme had various problems. Therefore, I just rebuilt it from scratch. Please try the latest one from repo.

**Comment by El-Zipo** [comment]
@nana-4 
I don't like the new blue colour (color) when hoveing the mouse in sidebar of Gnome files.
And also now Flat-plat is looks like Paper theme.
Old colours are great.

**Comment by Skehmatics** [comment]
@El-Zipo conversations about the color scheme might be better suited in issue #19

Also, consider forking the repo and changing the colors in gtk-3.0/_colors.scss to your tastes (remember to run the parse-sass.sh build script)

**Comment by El-Zipo** [comment]
@Skehmatics  I didn't mention about the pink colour and also I don't like it.
I'm telling about the blue colour and the gray colour header bar.
White colour is great.
But gray colour is matches with paper icon theme. 
But blue colour ????? :(

**Comment by jayarc** [comment]
Nana-4 thanks for you response and thanks for you hard work putting this theme together. I will get the lastest code :) I've seen the way Adapta offers up a configuration file for the "major" colors in the theme, creating a $sass variable that's later available in all the stylesheets. I kind of assume there will be more people asking about that so, less future work. If I have the time soon I could put up a pull request.

**Comment by nana-4** [comment]
@jayarc Ok, thanks!
