### ISSUE TITLE
 Ugly selection highlighting on xfce

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/Flat-Plat#52]
I'm using version 3.20.20160404 of this theme on xfce 4.12. This theme is very nice, but on xfce (and other d.e.?) there is an annoying gray box on selected items. It should be easy to remove, but unfortunately I have never worked with gtk themes :(
![screenshot_2016-07-16_10-46-41](https://cloud.githubusercontent.com/assets/7833001/16893819/f30fc80e-4b43-11e6-98eb-fdd08ad62ed9.png)
![screenshot_2016-07-16_10-46-30](https://cloud.githubusercontent.com/assets/7833001/16893820/f319ff72-4b43-11e6-944c-6d84321eeb44.png)

**Comment by nana-4** [comment]
I'm sorry for late reply.
It is by design. Those rings show the focus state.
But you can remove it by editing the `gtkrc` file in the `gtk-2.0` directory:

```
 # Focuslines

 image 
 {
     function                    = FOCUS
     file   = "Others/focus.svg"
     border   = { 2, 2, 2, 2 }
     stretch   = TRUE
        }
```

to

```
 # Focuslines

 image 
 {
     function                    = FOCUS
 }
```

If you using master branch, edit around `"assets/focus.png"` in the `main.rc` file.
