### ISSUE TITLE
non flat buttons

### ISSUE THREAD

**Issue by mrlotfi** [nana-4/Flat-Plat#53]
Everything seems flat in this beautiful theme but buttons (i exactly mean normal buttons in windows. eg rhythmbox play and pause button) are not flat and have shadows. Don't you think they look better without shadows?

**Comment by cthbleachbit** [comment]
In material Design guidelines, GUI elements do have depth properties and can be above or below other elements. So shadow effect is the visual representation of depth of an element.

**Comment by El-Zipo** [comment]
Yeah, But without depth is the best.
Check the buttons in Adapta theme.

**Comment by Skehmatics** [comment]
This theme is based on Google's material design, which differs from purely flat design. Shadows are important here, as they indicate the state of a button. 

https://material.google.com/components/buttons.html

**Comment by metarmask** [comment]
The spec that @Skehmatics linked says there are FABs, raised and flat buttons. Flat buttons should be used to not create too many depth layers. It also says that buttons should be uppercase.

**Comment by nana-4** [comment]
Okay, I will flatten buttons on the part of toolbars (e.g. Rhythmbox).

**Comment by nana-4** [comment]
@metarmask 
I almost agree. However,
> It also says that buttons should be uppercase.

GNOME/GTK buttons might contain a proper noun. (e.g. font name, file name, etc.)
I think they shouldn't be uppercase, so I'm reluctant to implement it.

**Comment by metarmask** [comment]
@nana-4 I agree not all buttons would look good but some one-two word buttons could use a bit of uppercase.

**Comment by nana-4** [comment]
@metarmask Hmm, unfortunately, it is not technically easy IMHO.
