### ISSUE TITLE
Strange switches in dconf Editor

### ISSUE THREAD

**Issue by flipflop97** [nana-4/Flat-Plat#54]
![screenshot from 2016-07-21 16-05-44](https://cloud.githubusercontent.com/assets/13943260/17025631/08b2b582-4f5d-11e6-8dda-8d0e7fd88325.png)
In the above screenshot (open dconf editor and click any value) there's a switch in the lower right that doesn't look like it should (wide and stretched).

**Comment by nana-4** [comment]
Maybe its switchs width are hard-coded. But I've added a slight modification.
![image](https://cloud.githubusercontent.com/assets/9556384/17461811/d072ecb2-5cd3-11e6-9ce3-035bd6182629.png)
