### ISSUE TITLE
LibreOffice

### ISSUE THREAD

**Issue by sharifzadesina** [nana-4/Flat-Plat#57]
There are some bugs in LibreOffice which you can see them in below images.

Gnome 3.18.4
LibreOffice 5.1.2.2

![2016-07-27_14-25-19](https://cloud.githubusercontent.com/assets/15300551/17172110/d92a268c-5408-11e6-960a-6701bbaa4754.png)
![2016-07-27_14-26-24](https://cloud.githubusercontent.com/assets/15300551/17172111/d9318602-5408-11e6-9b50-d833756be295.png)

**Comment by nana-4** [comment]
Thank you for your bug report. I just fixed the text color.
However, the second issue is reproduced in other themes, so I think that it is upstream issue.
