### ISSUE TITLE
Dark color top bar for Unity

### ISSUE THREAD

**Issue by El-Zipo** [nana-4/Flat-Plat#58]
Icons in the top bar look nearly invisible.
Please change the top bar's color to dark.
![candy5](https://cloud.githubusercontent.com/assets/19838220/17467276/150fb948-5d3a-11e6-9cec-39464b339aa5.png)

**Comment by El-Zipo** [comment]
Papirus icons are nearly invisible.
Paper icons are completely invisible.

**Comment by nana-4** [comment]
It was supported with 2cd76e49eb9c4719d76143bd78fc8a572333b43f.
