### ISSUE TITLE
Theme is not showing in Unity tweak tool

### ISSUE THREAD

**Issue by El-Zipo** [nana-4/Flat-Plat#62]
This theme is not listed in the themes list of unity tweak tool.
Why this ????
But this theme is showing in Gnome tweak tool.

**Comment by nana-4** [comment]
Sorry for the late reply.
I don’t know why, but it seems to require a Metacity theme.

**Comment by nana-4** [comment]
It was supported with a7cc6778b9b0e44708257d7ef1761810e8e4b47b.
