### ISSUE TITLE
Ubuntu Dark title's for some application

### ISSUE THREAD

**Issue by rahilwazir** [nana-4/Flat-Plat#63]
Below applications have black/dark titles in `Ubuntu 16.04/xenial GTK 3.18`:

**Thunderbird**:

![thunderbird](https://cloud.githubusercontent.com/assets/1818941/17892086/f0e25532-6958-11e6-8e99-f57ab8679631.png)

**Jetbrains PHPStorm** (Settings -> Appearance -> Theme = GTK+):

![phpstorm](https://cloud.githubusercontent.com/assets/1818941/17892252/b7520c26-6959-11e6-9c96-21058667e5ed.png)

**Comment by spegoraro** [comment]
+1 Same here using 3.20 with the latest master.

**Comment by nana-4** [comment]
Thank you for your bug report. :)

**Comment by rahilwazir** [comment]
@nana-4 This isn't merged to `3.18` branch yet? :cry:

**Comment by nana-4** [comment]
@rahilwazir I've merged this. :)
