### ISSUE TITLE
Radio buttons and checkboxes too big

### ISSUE THREAD

**Issue by gregorydk** [nana-4/Flat-Plat#68]
In short, Adapta had the same issue. Resizing to a smaller size solves the bug.
See https://github.com/tista500/Adapta/issues/61

**Comment by nana-4** [comment]
The size of the check/radiobuttons are based on Material design guidelines.
See here: https://material.google.com/components/selection-controls.html
and here of `Keyline shapes` : https://material.google.com/style/icons.html#icons-system-icons

And I think 16px is a bit too small. :(

**Comment by gregorydk** [comment]
I'll learn to live with it. :-)
