### ISSUE TITLE
Animations on checkbuttons/radiobuttons

### ISSUE THREAD

**Issue by Salamandar** [nana-4/Flat-Plat#7]
I really don't know if an animation as we can see in Android is doable.
Maybe a ripple animation for the new drawable to appear ? (a "png" ripple)

**Comment by nana-4** [comment]
In checkbuttons/radiobuttons, GTK3 is currently not support CSS transition/animation...
Because there is technical limitation, I changed their design.

**Comment by Salamandar** [comment]
Sorry for no answer ^^
Okay, i understand that. :)

**Comment by Salamandar** [comment]
With Gtk3.20 it's not a limitation anymore :D

**Comment by nana-4** [comment]
It was supported in GTK+ 3.20.
