### ISSUE TITLE
GTK 3.22 theme

### ISSUE THREAD

**Issue by USBA** [nana-4/Flat-Plat#70]
- - -
* Desktop environment (and version) : GNOME 3.22
* GTK+ 3 version : 3.22

GNOME 3.22 is set to be released on September 21, 2016. 
Therefore need a Flat-Plat gtk 3.22 theme.

Thanks.

**Comment by nana-4** [comment]
I'm going to release v3.22 before September 21. ;)

**Comment by USBA** [comment]
:smiley: 
I'm also waiting for the flat-plat theme version with light title bars.
Thanks @nana-4

**Comment by atompie** [comment]
Is there any chance for light top bars theme?

**Comment by nana-4** [comment]
@atompie Yes, I'm going to release the light title bar version in the near future.

**Comment by nana-4** [comment]
Released this.

**Comment by atompie** [comment]
@nana-4  How can I configure flat-plat to use light bar version. Is there any information on configuration on github?

**Comment by nana-4** [comment]
@atompie I'm so sorry for the delay, but light bar version is still not available (because there are some onerous problems..). However, I will undertake this now, so please wait a moment.
