### ISSUE TITLE
Thunderbird toolbar

### ISSUE THREAD

**Issue by jgato** [nana-4/Flat-Plat#71]
hi there,

The theme is absolutly awesome, the only issue that I have is with thunderbird tool bar

![screenshot from 2016-09-05 08-18-21](https://cloud.githubusercontent.com/assets/3435696/18238898/7e335340-7341-11e6-9aa4-d9b33a245f31.png)

Is there any easy way to solve it? I could try with other Thunderbird Themes, but they are not really good looking. I am using Gnome-shell 3.18.

Many thanks

**Comment by nana-4** [comment]
Thank you for your bug report. It was fixed with #63. I'll release modified version in the near future. 😃
