### ISSUE TITLE
gnome shell theme : some characters are hard to be recognized

### ISSUE THREAD

**Issue by mcjoeng** [nana-4/Flat-Plat#72]
* debian 8 
* gnome 3.14
* GTK+ 3.14
* Flat-Plat version : 3.14.20160821
* Screenshot(s)
.
Look at the screenshot and the annotate
.
![2016-09-11 14 09 42](https://cloud.githubusercontent.com/assets/10485304/18415611/0e87f1c4-782b-11e6-8a9a-dff62bda38aa.png)

**Comment by nana-4** [comment]
Thank you for your bug report. 👍 
I believe it was resolved...
