### ISSUE TITLE
Eclipse tooltips appear as white text on white background

### ISSUE THREAD

**Issue by junrrein** [nana-4/Flat-Plat#73]
> **Note:** Before submitting an issue, please check whether it also occurs with other themes.

This doesn't happen with the Adwaita or Arc themes.

* Distribution (and version)

Opensuse Tumbleweed

* Desktop environment (and version)

Budgie                 10.2.7
Gnome-shell      3.20.4

* GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)

Gtk 3.20.9

* Flat-Plat version

v3.20.20160821, Laptop variant.

* Related application version

Eclipse Neon (4.6) (using Gtk3 through SWT)

* Steps to reproduce

1 - Close any open instances of Eclipse.
2 - Change the desktop theme to Flat-Plat-laptop
3 - Open Eclipse.
4 - With the mouse pointer, hover over a compiler error.
5 - The tooltip tha appears has white text on white background.

* Screenshot(s)

Eclipse when using the Arc theme:

![eclipse arc](https://cloud.githubusercontent.com/assets/962049/18567529/f8a3d4f8-7b6e-11e6-9e96-7a460998f0b7.png)

Eclipse when using the Flat-Plat-laptop theme:

![eclipse flat-plat](https://cloud.githubusercontent.com/assets/962049/18567540/040ea692-7b6f-11e6-90ad-dbb9a7a96be3.png)

**Comment by junrrein** [comment]
I tested Flat-Plat from git master and the issue is also present there.

**Comment by junrrein** [comment]
I can confirm this issue is no longer present in git master. Thanks for developing this theme! It's awesome.

**Comment by nana-4** [comment]
@junrrein Thanks! 😃
