### ISSUE TITLE
[Light theme] Pop-ups on Epiphany have a titlebar with white text over a light gray background

### ISSUE THREAD

**Issue by junrrein** [nana-4/Flat-Plat#76]
> **Note:** Before submitting an issue, please check whether it also occurs with other themes.

The issue doesn't happen in the Flat-Plat dark variant.

>* Distribution (and version)
>* Desktop environment (and version)
>* GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
>* Flat-Plat version
>* Related application version

Same environent as in issue #75.

* Steps to reproduce

1 - Set the Flat-Plat light variant as your application theme.
2 - Trigger a pop-up in Epiphany. For example, in [this page](https://build.opensuse.org/request/show/427966#), on the "Build Results" panel, click on any "blocked" label.

* Screenshot(s)

Flat-Plat, dark variant

![flat-plat dark popup](https://cloud.githubusercontent.com/assets/962049/18618391/62284f18-7dbc-11e6-9dae-e6b2517243d8.png)

Flat-Plat, light variant

![flat-plat light popup](https://cloud.githubusercontent.com/assets/962049/18618394/68def9ba-7dbc-11e6-9a72-e21fcfaa00be.png)

**Comment by junrrein** [comment]
Thank you!

**Comment by nana-4** [comment]
Thank you for the report. :)
