### ISSUE TITLE
Please restore the alternating colors of table rows

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/Flat-Plat#77]
I'm using the latest version of this theme on arch linux xfce, and it seems that the color of rows in tables are no longer different. Maybe it's just a habit, but to me it seemed useful.

Example of alternate rows:
![screenshot_2016-09-23_14-55-25](https://cloud.githubusercontent.com/assets/7833001/18786662/5ce13cc2-819f-11e6-9329-535482510e55.png)

Latest version of this theme:
![screenshot_2016-09-23_14-56-57](https://cloud.githubusercontent.com/assets/7833001/18786669/66c29542-819f-11e6-8df1-3a5f94fd2d72.png)

**Comment by nana-4** [comment]
Hmm, I think the old style doesn't fit to this theme. Also there is no style like the alternating color rows in Material Design guidelines. So I cannot accept it, sorry.

However, you can restore the style by rewriting `gtk-2.0/main.rc`.
Remove the following rows (lines 92-95):
```
  GtkTreeView::allow-rules          = 0
  # Set this because some apps read it
  GtkTreeView::odd-row-color        = @base_color
  GtkTreeView::even-row-color       = @base_color
```

**Comment by nana-4** [comment]
@CreamyCookie According to the [GTK+ 3 doc](https://developer.gnome.org/gtk3/stable/GtkTreeView.html#GtkTreeView--s-allow-rules), adding the following code to `gtk.css` or `gtk-dark.css` should work:

```css
* {
  -GtkTreeView-allow-rules: 1;
  -GtkTreeView-even-row-color: #EEEEEE;
}
```

but strange, it doesn't work in my environment (GTK+ 3.24.1). Probably this is an upstream bug, unfortunately.

**Comment by CreamyCookie** [comment]
Thank you! Yeah seems like a bug report was opened 3 years ago: https://gitlab.gnome.org/GNOME/gtk/issues/581
