### ISSUE TITLE
App indicators are in wrong positions

### ISSUE THREAD

**Issue by cthbleachbit** [nana-4/Flat-Plat#8]
When using the dash to dock extension, I noticed that the indicators are always on the left side of the icons like this

![screenshot from 2015-11-03 21-15-47](https://cloud.githubusercontent.com/assets/3353318/10909024/dd1e8554-8270-11e5-9970-fae6d30bf2bd.png)

The indicators should be like this if the dock is placed at the bottom of the screen:

![screenshot from 2015-11-03 21-15-39](https://cloud.githubusercontent.com/assets/3353318/10909047/03a38d32-8271-11e5-95ee-7f74aec467f7.png)

**Comment by nana-4** [comment]
Thank you for your bug report.
I'm going to fix it.
