### ISSUE TITLE
Evolution menu bar renders weirdly.

### ISSUE THREAD

**Issue by garethmcc** [nana-4/Flat-Plat#81]
![evolutionmenubar](https://cloud.githubusercontent.com/assets/4112280/19385509/226a932e-920f-11e6-801a-13355ec4d5be.png)

**Comment by nana-4** [comment]
I'm sorry for being so late in reply...but your report information is too little, so I can't help you. Did you see the [issue template](https://github.com/nana-4/Flat-Plat/blob/master/.github/ISSUE_TEMPLATE.md)? Anyway, it seems you have installed the wrong version of the theme.

**Comment by nana-4** [comment]
There's no response, so I close this issue.
