### ISSUE TITLE
Slider Transparent when Animations Enabled

### ISSUE THREAD

**Issue by TBJ** [nana-4/Flat-Plat#82]
When animations are enabled in tweak tool, the slider circles show up transparent:

![screenshot from 2016-10-14 09-08-50](https://cloud.githubusercontent.com/assets/22847104/19405080/92b682c8-9228-11e6-9eb0-d5f4556b7419.png)

If animations are disabled the sliders are no longer transparent and are filled in with pink. It only seems to happen when a slider is toggled after enabling animations.

Happens on Flat Plat 3.20 and 3.22, both in compact and non compact versions and on builds 20160821 and 20160921. Works correctly on old build 20160404.

Arch, gnome, gtk3.22.1

**Comment by Skehmatics** [comment]
Happens to me too. Ubuntu 16.10 with gnome-shell 3.22.1

**Comment by nana-4** [comment]
Sorry for the late response. I had a hard time fixing it..
