### ISSUE TITLE
Libreoffice menu text color (or backgund) and no hover effect

### ISSUE THREAD

**Issue by meson11** [nana-4/Flat-Plat#83]
At first i was sceptic about the new color-scheme but now i like it very much.
In Libreoffice i encounterted two bugs:
First: The menu text color ist white on light gray ground
Second: there are no hover effects at the menu entrys and the icons. in the screenshot the cursor is above the pdf-icon.
- Distribution: Manjaro
- Desktop environment: Gnome 3.20
- GTK+ 3 version: 3.20
- Flat-Plat version: v3.20.20160921
- Related application version: Libreoffice 5.1.5.2
- Steps to reproduce: open Libreoffice
- Screenshot
  ![libreofficetextcolornohover](https://cloud.githubusercontent.com/assets/22944649/19537555/b552cdba-9650-11e6-8c5d-96eb969beafd.jpg)

**Comment by meson11** [comment]
With Libreoffice 5.2.2.2.0+ the menu works but the icons still have no hover effect.
![libreoffice5 2 2](https://cloud.githubusercontent.com/assets/22944649/19578563/87425cf2-971c-11e6-8c9e-054d0940dd43.jpg)

**Comment by wimstefan** [comment]
Libreoffice 5.2.3.3 on Gentoo system here and I still have white text on light gray background in the menus :-/
Anything I can do to change that?

**Comment by nana-4** [comment]
@wimstefan 
On my system (Fedora 24 and 25) the menus render correctly.
So I don't have any good ideas at this point. :worried:
But there seems to be sometimes fixed by installing again.

**Comment by wimstefan** [comment]
@nana-4: Thanks for taking the time to reply! I'm already installing Libreoffice again with different USE-flags in the hope that it'll fix the problem. It's just a bit time-consuming since I have to re-compile Libreoffice from source ;-)

What I also notice btw is that Thunderbird has a dark background in the menus with a dark font ... ;-) No idea how to tackle that either ...

Which other apps do you recommend to re-install?

**Comment by nana-4** [comment]
> Thanks for taking the time to reply!

You’re welcome!

> What I also notice btw is that Thunderbird has a dark background in the menus with a dark font

Really? It should have already been fixed. Maybe you are using an older Flat-Plat version? The [latest stable version](https://github.com/nana-4/Flat-Plat#installation) is released on November 9th.

> Which other apps do you recommend to re-install?

Sorry I don't know the details, but only Libreoffice should be okay...

**Comment by wimstefan** [comment]
Hmmm - I'm using the latest git version of Flat-Plat ... so it should be fixed ...
I'll add a screenshot to make it more clear.
![thunderbird-flat-plat-gtk-2016-11-15-16-13](https://cloud.githubusercontent.com/assets/4605934/20311087/b42e72f0-ab4e-11e6-98bc-9d92ee579978.png)

**Comment by nana-4** [comment]
@wimstefan 
Hmm. I've never used awesome, but in order to properly render them for awesome, it may be necessary to have its specific styling. I'll investigate if there is time. Sorry I couldn't help this time.

The image is an example of display in the GNOME shell 3.20.

![image](https://cloud.githubusercontent.com/assets/9556384/20312090/910c71a4-ab95-11e6-85ee-d01fe26023af.png)

**Comment by sbsbs15** [comment]
Hi @nana-4 , I see that the no hover effect appers only when use libreoffice in gtk3 mode(exporting the SAL_USE_VCLPLUGIN=gtk3 environment variable). On the other hand I've noticed that the Adapta theme fixed this, so I think in his code may be the solution.

I also want to highlight that some buttons don't have any border and without it you can't distinguish them.
Example:
![captura de pantalla de 2017-03-04 14-26-30](https://cloud.githubusercontent.com/assets/15521217/23579125/03418ba0-00e7-11e7-9053-4b7c953ad182.png)

I hope this tips can help you to fix it... and thank you for your work in this amazing theme :)

**Comment by nana-4** [comment]
@sbsbs15 Thank you for your help.

I tackled a little to solve those problems (e.g. referred to Adapta's code or tried other methods) and I understood somewhat of workarounds. However, unfortunately, applying specific styles to Libreoffice seems much more difficult than for other apps.

So I need more time and contemplation to solve those problems. But I will work on it in the near future. Thanks. :)

**Comment by nana-4** [comment]
I fixed the hover effect issue in recent updates.

**Comment by sbsbs15** [comment]
@nana-4 Thank you!!
