### ISSUE TITLE
pane separator line renders black/transparent

### ISSUE THREAD

**Issue by baurigae** [nana-4/Flat-Plat#84]
First I want to congratulate you on an overall wonderful theme, and thank you for sharing it with the community.

As for the issue I'm reporting - 

![i](https://cloud.githubusercontent.com/assets/5447269/19695844/09ba2e96-9ae5-11e6-8a85-2738e0a5993a.png)

-this is an old bug that I noticed in your theme, and in a fork of your theme ([this](https://github.com/adapta-project/adapta-gtk-theme) one) a long time ago. I run Ubuntu 16.04 with Gnome 3.20, btw. So the fork got the issue fixed eventually, but I prefer this theme and I see the fix has not been contributed back to you, so, I'm filing this bug.

Here's the problem: a black - and then, sometimes transparent - 1px line renders instead of the normally light-gray styled vertical pane separator in Nautilus ("Files").
But this only happens when I switch to a new directory, and then only the first time I right-click on a folder/file to do whatever.
As I switch around directories a lot and right-click a lot in my workflow - even if this may seem like a minor issue to many people - to me it's really visually jarring.

So if and when you've time please look into it, either to try and fix it, or to give me some pointers as to how I might do it myself - I've already looked at the code, but no luck so far.

I also want to ask an unrelated question (I don't think it warrants opening an actual "issue"): how do I enable the light titlebars option in this theme? 
Anyway, thanks & cheers :)

**Comment by nana-4** [comment]
I'm sorry for the late reply, and thanks for your polite report. :)

I tried to reproduce this issue, but I couldn't.
I don't know whether it will resolve, but could you please test by adding the following code to the `gtk-3.0.css`? It's okay in any line:

```
.nautilus-window paned {
  background: #FFFFFF; }
```

If it seems to be fixed, I'll commit this. ;)

P.S. The light titlebar version is now available. Sorry for the delay.

**Comment by baurigae** [comment]
Thanks for looking into it!
So I've added that code to the latest release (at press time :) Flat-Plat-light-3.20.20161109 - 

and I have some bad and some good news:

bad news; the bug's still present, but now randomly. It used to appear without fail each time I switched to a new directory and right-clicked a folder/file, and now it happens, well, randomly. I'd say, 1 times out of 4.

Good news: I've found another way to reproduce the bug on my setup: grabbing and dragging (left or right) the actual separator handle of the Nautilus sidebar makes the 1px thing turn #000 while I'm click-and-dragging it  - and then when I release it, it returns to the intended styling (light gray).

**Comment by nana-4** [comment]
I tried another way to reproduce the bug, but unfortunately I failed.
However, I came up with another workaround.
So could you please test [this](https://raw.githubusercontent.com/nana-4/Flat-Plat/5a9a16614ab21c79003bc08d1869203f535f861e/gtk-3.0/gtk.css) again?

**Comment by baurigae** [comment]
Tested, and it fixes it here. 

Thanks!
