### ISSUE TITLE
Title bar buttons are white on a light background

### ISSUE THREAD

**Issue by jwhipp** [nana-4/Flat-Plat#85]
- Distribution (and version) - Ubuntu 16.10
- Desktop environment (and version) - Unity 7.5.0
- GTK+ 3 version (You can check it with `pkg-config --modversion gtk+-3.0`)
- Flat-Plat version - Tried Master, v3.22.20160921, 3.20
- Related application version - N/A
- Steps to reproduce

Check out, theme and set.
- Screenshot(s)
  ![selection_002](https://cloud.githubusercontent.com/assets/556332/19775867/28ef5b6a-9c2f-11e6-94a5-9a97fdda475c.png)

Hard to see the buttons in the screenshot, they are there just white.

**Comment by nana-4** [comment]
Thank you for the report!
