### ISSUE TITLE
Dark-side version

### ISSUE THREAD

**Issue by phackwer** [nana-4/Flat-Plat#86]
Do you think it would be possible to you to create a darker version, only black and shades of grey instead of the current colors? Your theme is by far the best I found for flat (all metrics are perfect). I just wanted something darker. 

Or could you at least point me the current colors used so I can "sed" them recursively and replace for darker colors on a fork? Last time I forked a theme the original had small changes from component to component and it took me a lot of time to make it all darker.

Since I code, I look at the screen for hours everyday (between 10 to 16 - once I coded 48 hours straight!) so having a darker desktop is almost a requirent for me.

https://github.com/phackwer/spacegray/blob/master/Screenshots/spacegray-midnight.png
https://github.com/phackwer/eclipse-gnome-dark/blob/master/screenshot_midnight_devil.png

Kind of a fan of the dark side of themes... (3.14 had great colors, but now I'm using 3.18 and the pink was a big shock).

**Comment by Skehmatics** [comment]
All of the colors are contained in gtk-3.0/_colors.scss and gnome-shell/_colors.scss

Edit those colors however you want, run the parse-scss.sh script, and you'll be good to go! 

Also, you might want to check out the "dark-theme" branch of my fork: https://github.com/Skehmatics/Flat-Plat/tree/dark-theme?files=1

**Comment by nana-4** [comment]
I'm sorry for the late reply.

The color scheme which is too dark is hard to produce material texture and it is not easy on the eyes for many people, ＩＭＨＯ. Therefore it is difficult to officially provide a color scheme close to black.
However I'd like to make the current dark theme somewhat darker.

**Comment by nana-4** [comment]
I'm so sorry that the correspondence was very delayed.
I don’t know if you like it, but I darkened the dark theme somewhat with 8602f26151d8b25925ced4cb6d75048ae527aeb4.
So I'd like to close this.

P.S. I also wrote how to change the accent (_pink_) color with 27205e37a8e8420583d4679f74a418a7903c8b30.
Please refer [`HACKING.md`](../blob/master/HACKING.md) if you are interested in changing it.
