### ISSUE TITLE
Other Bugs in Liebreoffice (popupmenus)

### ISSUE THREAD

**Issue by meson11** [nana-4/Flat-Plat#88]
All concerning popup menus
1. Unchecked checkboxes are invisible
2. Textfields are invisible
3. the light grey of the elements are barley visible on the white ground. 

switch the background to the light grey and the elements to white would solve all problems, i think

Distribution: Manjaro
Desktop environment: Gnome 3.22
GTK+ 3 version: 3.22
Flat-Plat version: v3.20.20160921
Related application version: Libreoffice 5.2.2.2.0+
Steps to reproduce: open Libreoffice
Screenshot

![checkbox](https://cloud.githubusercontent.com/assets/22944649/20170062/0ab81c0c-a72b-11e6-9998-2aec9c2becc8.png)
![textfield](https://cloud.githubusercontent.com/assets/22944649/20170063/0ab89330-a72b-11e6-8424-2947c8d0ca8a.png)

**Comment by gregorydk** [comment]
Is this getting a fix? The reason I'm currently not using Flat-Plat is because of this issue.

**Comment by nana-4** [comment]
Sorry but this has not been fixed yet, except for invisible checkbox/radio.

Unfortunately, it seems to be difficult to change style only for Libreoffice without affecting other apps.

I'd like to clarify the (duplicate) issues, so I opened a new issue as #122.

So I'd like to close this now, but thank you for your report. :)
