### ISSUE TITLE
Bad text in Shell

### ISSUE THREAD

**Issue by MichaelTiebesl** [nana-4/Flat-Plat#9]
Hi there,

Is it just me or more people have this after update today, with the gnome-shell and gnome-shell-extensions in Arch? I can see or read the text anymore. Text with Adwaita theme is normal to me.
I have Gnome 3.18 in Arch installed.

![schermafdruk van 2015-11-13 14-05-47](https://cloud.githubusercontent.com/assets/10792019/11139901/d01dc4e0-8a0f-11e5-80a6-396fd27932a5.png)

**Comment by cthbleachbit** [comment]
seems problems with locale. en_US.UTF8 is working normally, seems you are using German?

**Comment by MichaelTiebesl** [comment]
@cthbleachbit thanks for your reply. Asking myself now if there is a problem with locale, why is it with the default Adwaita the Gnome Shell correct?

**Comment by MichaelTiebesl** [comment]
After the re-install from the theme, the text was back to normal.
