### ISSUE TITLE
Round corner problem.

### ISSUE THREAD

**Issue by ZouhairEz** [nana-4/Flat-Plat#90]
I like to have the corners rounded, but when i try to realize that, something going wrong, look at the picture below.
![round-probem](https://cloud.githubusercontent.com/assets/22919035/20578192/ff711d74-b1bd-11e6-9a04-191a76ac97d7.png)

**Comment by nana-4** [comment]
I can't see it in my environment. (tested gnome 3.20 on Xorg and gnome 3.22 on Wayland)
![image](https://cloud.githubusercontent.com/assets/9556384/20579219/ea0ded62-b20e-11e6-95bf-6e81baf5af1f.png)
What version are you using?
Did you see the [issue template](https://github.com/nana-4/Flat-Plat/blob/master/.github/ISSUE_TEMPLATE.md)?

**Comment by ZouhairEz** [comment]
It is fine whit me too, just i like to see my corners rounded more than 2px, and when i try to put for ex 4px i see the black thing.

**Comment by nana-4** [comment]
Oops, I misunderstood your comment.
It should be realized by rounding the `decoration`.

```
decoration {
  border-radius: 4px 4px 0 0;
}
```

**Comment by ZouhairEz** [comment]
The black thing still visible, dont worry about it, 2px its fine. Thank you for that gorgeous theme, its the only reason why i use gnome. Merci :)

**Comment by ZouhairEz** [comment]
Ok, its works, the black thing is gone, thank you again. :)
