### ISSUE TITLE
Bug (?) in text fields

### ISSUE THREAD

**Issue by matteoalessiocarrara** [nana-4/Flat-Plat#93]
I'm using this theme (v3.22.20161109) on arch linux xfce (4.12). Gtk 3 version is 3.22.5.
The first character in text fields does not coincide with the beginning of the same. As can be seen in the attached picture, there is a space on the left.
![screenshot_2016-12-10_17-45-32](https://cloud.githubusercontent.com/assets/7833001/21074777/8f824f46-bf01-11e6-90eb-d0b14d4ca6ce.png)

**Comment by nana-4** [comment]
There seem to be the invisible icons (`image`) in that text fields.
This is really an upstream bug, but I'll try to add a workaround.
![image](https://cloud.githubusercontent.com/assets/9556384/21237125/00bfe216-c341-11e6-8e4b-2a3b1dc2e838.png)

**Comment by dayfuaim** [comment]
BTW, the similar thing can be seen in the "+/-"-filelds. Too much space in the left, so I don't even see the numbers.
The same fields in:
Flat-Plat
![2016-12-22 13-25-32](https://cloud.githubusercontent.com/assets/1274699/21423029/e1827836-c84b-11e6-929c-0cfdf30b3621.png)
and Adapta
![2016-12-22 13-25-57](https://cloud.githubusercontent.com/assets/1274699/21423054/fe99733e-c84b-11e6-976f-f40833ad695c.png)

**Comment by nana-4** [comment]
@dayfuaim 
Thanks for your report.
The fields also seems to have invisible icons on the left and right.
