### ISSUE TITLE
Dropdown Menu "very compact"

### ISSUE THREAD

**Issue by curvi** [nana-4/Flat-Plat#96]
I'm using the newest Flat-Plat version on Gnome 3.22 Fedora 25 in Compact-Light edition (and shell extension).
In every dropdown menu with only few options available the display gets messed up.
The phenomenon gets worse, when less options are available - only one option is totally hidden between the up and down arrow!
Same thing in Flat-Plat light (non compact), no issues with dropdowns in Adwaita.

![screenshot from 2016-12-30 13-42-46](https://cloud.githubusercontent.com/assets/3583463/21565277/18ebf888-ce96-11e6-9685-a1032a7dc528.png)

**Comment by nana-4** [comment]
Sorry for the fix to be late.
It took time to identify the cause.

Thank you for the report!
