### ISSUE TITLE
I can't apply GDM login theme.

### ISSUE THREAD

**Issue by CNBLACK** [nana-4/Flat-Plat#97]
I'm using newest Flat-Plat version on Debian 9 Stretch RC1 with Gnome 3.22.
But I can't apply GDM Login theme. I followed your guide, but It is not work.

**Comment by nana-4** [comment]
Can you attach an error log?

**Comment by CNBLACK** [comment]
yeah, gnome-shell-theme.gresource file in Flat-Plat theme directory. But It is not work. So, I give up to apply that... :/
